version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tutor_backend
    volumes:
      - backend_sqlite_data:/app/data # Pomenovaný volume pre SQLite dáta
      # Pre live reload počas vývoja (môže spomaliť kontajner):
      # - ./backend/app:/app/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env # Načíta premenné z .env súboru backendu
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # Ak potrebuješ build argumenty (napr. API URL počas build time, hoci to neodporúčam pre tento prípad)
      # args:
      #   NEXT_PUBLIC_API_URL: http://localhost:8000 # Toto je pre build time, nie runtime
    container_name: tutor_frontend
    # Pre live reload počas vývoja (môže spomaliť kontajner a vyžaduje úpravy v Next.js configu pre Docker):
    # volumes:
    #   - ./frontend/src:/app/src
    #   - ./frontend/public:/app/public
    ports:
      - "3000:3000"
    environment:
      # Toto je dôležité! Frontend kontajner bude kontaktovať backend cez názov služby 'backend'
      NEXT_PUBLIC_API_URL: http://backend:8000
      # NODE_ENV: development # Môžeš nastaviť na development, ak chceš HMR, ale vyžaduje ďalšie nastavenia
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_sqlite_data: # Definícia pomenovaného volume pre perzistentné dáta