# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tutor_backend
    volumes:
      - backend_sqlite_data:/app/data
      - ./media_uploads:/app/media_files_data
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      MEDIA_FILES_BASE_DIR: /app/media_files_data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tutor_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: tutor_postgres_db
    restart: always
    environment:
      POSTGRES_USER: tutoruser
      POSTGRES_PASSWORD: tutorpassword
      POSTGRES_DB: tutordb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  backend_sqlite_data:
  postgres_data:
